### ISSUE TITLE
Project link is 404

### ISSUE THREAD

**Issue by dvyukov** [Rust-for-Linux/Rust-for-Linux.github.io#1]
Project link on the main page leads to https://github.com/orgs/Rust-for-Linux/projects/1 which is 404.
Not sure where it was supposed to lead, so can't fix myself.

**Comment by ojeda** [comment]
Thanks for catching that. We should just make the entire page/domain 301-redirect to https://github.com/Rust-for-Linux/linux for the moment.

**Comment by ojeda** [comment]
I am doing that now and removing this repo since we won't use it anymore.
